export default [
  {
    userId: 1,
    email: "sabbir@alam.com",
    name: "Md. Sabbir Alam",
    gender: "Male",
    age: "29",
    country: "Russia",
    city: "Kazan",
  },
  {
    userId: 2,
    email: "shabnam@mushrit.com",
    name: "Mushrit Shabnam",
    gender: "Female",
    age: "29",
    country: "UK",
    city: "LONDON",
  },
  {
    userId: 3,
    email: "sakib@alam.com",
    name: "Sakib Alam",
    gender: "Male",
    age: "27",
    country: "Russia",
    city: "Kazan",
  },
  {
    userId: 4,
    email: "akter@saima.com",
    name: "Saima Akter",
    gender: "Female",
    age: "24",
    country: "UK",
    city: "LONDON",
  },
];
